# Generated by Django 3.2.4 on 2021-06-28 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('institution_a', models.CharField(max_length=70)),
                ('institution_b', models.CharField(max_length=70)),
                ('contenu', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('dernier_modification', models.DateTimeField(auto_now=True, verbose_name='last modification')),
                ('etat', models.CharField(choices=[('en cours', 'En Cours'), ('signé', 'Signe'), ('validé', 'Valide'), ('réfusé', 'Refuse')], default='en cours', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('signature', models.ImageField(blank=True, max_length=255, null=True, upload_to='signatures')),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.convention')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.convention')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('creation', 'Creation'), ('signing', 'Signing')], default='creation', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='activity date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
